In [15]:
import tensorflow as tf
import numpy as np
import os
import random
import re

from batch_generators.java_batch_generator import JavaBatchGenerator

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
data_directory = '/home/sven/java_github_corpus'

In [ ]:
from collections import Counter
import javalang

subdirectories = [name for name in os.listdir(data_directory) if os.path.isdir(os.path.join(data_directory, name))]
count = len(subdirectories)
counter = Counter()
for i, s in enumerate(subdirectories):
    print('project {}/{}'.format(i, count))
    files = [name for name in os.listdir(os.path.join(data_directory, s)) 
              if not os.path.isdir(os.path.join(data_directory, s, name))]
    for file in files:
        with open(os.path.join(data_directory, s, file), 'r') as file_data:
            tokens = list(javalang.tokenizer.tokenize(file_data.read()))
            counter.update(tokens)

project 0/14435
project 1/14435
project 2/14435
project 3/14435
project 4/14435
project 5/14435
project 6/14435
project 7/14435
project 8/14435
project 9/14435
project 10/14435
project 11/14435
project 12/14435
project 13/14435
project 14/14435
project 15/14435
project 16/14435
project 17/14435
project 18/14435
project 19/14435
project 20/14435
project 21/14435
project 22/14435
project 23/14435
project 24/14435
project 25/14435
project 26/14435
project 27/14435
project 28/14435
project 29/14435
project 30/14435
project 31/14435
project 32/14435
project 33/14435
project 34/14435
project 35/14435
project 36/14435
project 37/14435
project 38/14435
project 39/14435
project 40/14435
project 41/14435
project 42/14435
project 43/14435
project 44/14435
project 45/14435
project 46/14435
project 47/14435
project 48/14435
project 49/14435
project 50/14435
project 51/14435
project 52/14435
project 53/14435
project 54/14435
project 55/14435
project 56/14435
project 57/14435
project 58/14435
project

In [33]:
batch_generator = JavaBatchGenerator(data_directory)
input_iterator = batch_generator.train_batch_generator(8)

In [34]:
print(input_iterator.next())

load projects


TypeError: float() argument must be a string or a number

In [21]:
subdirectories = [name for name in os.listdir(data_directory) if os.path.isdir(os.path.join(data_directory, name))]
count = 0
for s in subdirectories:
    if not os.listdir(os.path.join(data_directory, s)):
        count += 1
print(count)

0


In [9]:
a = np.array([[1,2,3],[1,2]])

In [10]:
print(a.shape)

(2,)


In [13]:
a = np.array([[1,2,3],[4], [5,6,7,8,9],[10,11]])

max_length = 0
sequence_lengths = []
for l in a:
    sequence_lengths.append(len(l))
    if len(l) > max_length:
        max_length = len(l)

b = np.zeros((len(a), max_length))
for i in range(len(a)):
    b[i][:sequence_lengths[i]] = a[i]
    
print(b)
print(b.shape)

[[ 1.  2.  3.  0.  0.]
 [ 4.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9.]
 [10. 11.  0.  0.  0.]]
(4, 5)
