In [1]:
import tensorflow as tf
import numpy as np
import os
import random
import re

from batch_generators.java_batch_generator import JavaBatchGenerator

%load_ext autoreload
%autoreload 2

/home/sven/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
data_directory = '/home/sven/java_github_corpus'

In [ ]:
from collections import Counter
import javalang

subdirectories = [name for name in os.listdir(data_directory) if os.path.isdir(os.path.join(data_directory, name))]
count = len(subdirectories)
counter = Counter()
for i, s in enumerate(subdirectories):
    print('project {}/{}'.format(i, count))
    files = [name for name in os.listdir(os.path.join(data_directory, s)) 
              if not os.path.isdir(os.path.join(data_directory, s, name))]
    for file in files:
        with open(os.path.join(data_directory, s, file), 'r') as file_data:
            tokens = list(javalang.tokenizer.tokenize(file_data.read()))
            counter.update(tokens)

project 0/14435
project 1/14435
project 2/14435
project 3/14435
project 4/14435
project 5/14435
project 6/14435
project 7/14435
project 8/14435
project 9/14435
project 10/14435
project 11/14435
project 12/14435
project 13/14435
project 14/14435
project 15/14435
project 16/14435
project 17/14435
project 18/14435
project 19/14435
project 20/14435
project 21/14435
project 22/14435
project 23/14435
project 24/14435
project 25/14435
project 26/14435
project 27/14435
project 28/14435
project 29/14435
project 30/14435
project 31/14435
project 32/14435
project 33/14435
project 34/14435
project 35/14435
project 36/14435
project 37/14435
project 38/14435
project 39/14435
project 40/14435
project 41/14435
project 42/14435
project 43/14435
project 44/14435
project 45/14435
project 46/14435
project 47/14435
project 48/14435
project 49/14435
project 50/14435
project 51/14435
project 52/14435
project 53/14435
project 54/14435
project 55/14435
project 56/14435
project 57/14435
project 58/14435
project

In [5]:
batch_generator = JavaBatchGenerator(data_directory)
input_iterator = batch_generator.train_batch_generator(8)

In [6]:
print(input_iterator.next())

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 1 0 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 1 0 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 1 1]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 1 0 0]
  [0 0 0 ... 0 1 1]]

 [[0 0 0 ... 0 0 1]
  [0 0 0 ... 1 0 1]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 1 1]
  [0 0 0 ... 1 0 1]
  [0 0 0 ... 0 1 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 0]
  [0 0 0 ... 0 1 1]]]


In [7]:
b = input_iterator.next()

In [19]:
c = np.packbits(b, axis=2)
for e in c:
    for f in e:
        print(chr(f[1]))
    print('')

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
i
m
p
o
r
t
 
a
n
d
r
o
i
d
.
o
s
.
B
u
n
d
l
e
;

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
}
 
e
l
s
e
 
{

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
p
u
b
l
i
c
 
v
o
i
d
 
o
n
L
o
g
i
n
C
o
m
p
l
e
t
e
d
(
)
 
{

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
p
u
b
l
i
c
 
v
o
i
d
 
s
e
t
Q
o
s
(
Q
o
S
 
q
o
s
)
 
{

r
o
u
t
e
s
.
p
u
t
(
s
t
a
r
t
s
W
i
t
h
,
 
n
e
w
 
S
i
m
p
l
e
R
e
s
p
o
n
s
e
H
a
n
d
l
e
r
(
s
t
a
r
t
s
W
i
t
h
)
)
;

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
}

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
}

�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
�
}
)
;



In [20]:
for c in "hello world":
    print(c)

h
e
l
l
o
 
w
o
r
l
d


In [10]:
print(a.shape)

(2,)


In [13]:
a = np.array([[1,2,3],[4], [5,6,7,8,9],[10,11]])

max_length = 0
sequence_lengths = []
for l in a:
    sequence_lengths.append(len(l))
    if len(l) > max_length:
        max_length = len(l)

b = np.zeros((len(a), max_length))
for i in range(len(a)):
    b[i][:sequence_lengths[i]] = a[i]
    
print(b)
print(b.shape)

[[ 1.  2.  3.  0.  0.]
 [ 4.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9.]
 [10. 11.  0.  0.  0.]]
(4, 5)


In [22]:
tf.reset_default_graph()

input = tf.placeholder(tf.float32, shape=(128, None, 5), name='input')
target = tf.placeholder(tf.float32, shape=(128, None, None), name='target')

batch_generator = JavaBatchGenerator(data_directory)

rnn_layers = [tf.nn.rnn_cell.LSTMCell(256) for i in range(2)]
multi_rnn_cell = tf.nn.rnn_cell.MultiRNNCell(rnn_layers)
encoder_outputs, encoder_state = tf.nn.dynamic_rnn(cell = multi_rnn_cell,
                                                    inputs = input,
                                                    dtype = tf.float32)